/*
 * Author: Riley Chai
 * Class: ICS4U
 * Program: Recursion Assignment Part B GUI
 */

/**
 *
 * @author 335480661
 */

//Part 8
public class Components extends javax.swing.JPanel {

    /**
     * Creates new form Components
     */
    //Default values
    public static int WallDistance = 1000;
    public static int Speed = 50;
    public static double percentJumped = 0.50;

    public Components() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        wallDistanceSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        speedSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        percentJumpedSlider = new javax.swing.JSlider();
        startButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        jLabel1.setText("Wall Distance: 1000");

        wallDistanceSlider.setMaximum(1000);
        wallDistanceSlider.setMinimum(100);
        wallDistanceSlider.setValue(1000);
        wallDistanceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wallDistanceSliderStateChanged(evt);
            }
        });

        jLabel2.setText("Speed(ms): 50");

        speedSlider.setMaximum(2000);
        speedSlider.setMinimum(10);
        speedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                speedSliderStateChanged(evt);
            }
        });

        jLabel3.setText("% Distance Jumped: 50");

        percentJumpedSlider.setMinimum(10);
        percentJumpedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                percentJumpedSliderStateChanged(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(wallDistanceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(percentJumpedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quitButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wallDistanceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentJumpedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wallDistanceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wallDistanceSliderStateChanged
        WallDistance = wallDistanceSlider.getValue();//Retrieves the wall distance when the slider is adjusted.
        jLabel1.setText("Wall Distance: " + WallDistance);//Updates the label with the new value.
    }//GEN-LAST:event_wallDistanceSliderStateChanged

    private void speedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_speedSliderStateChanged
        Speed = speedSlider.getValue();//Retrieves the speed when the slider is adjusted. 
        jLabel2.setText("Speed(ms): " + Speed);//Updates the label with the new value.
    }//GEN-LAST:event_speedSliderStateChanged

    private void percentJumpedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_percentJumpedSliderStateChanged
        percentJumped = percentJumpedSlider.getValue();//Retrieves the percent jumped value when the slider is adjusted.
        jLabel3.setText("% Distance Jumped: " + percentJumped);//Updates the label with the new value.
        percentJumped = percentJumpedSlider.getValue() * 0.01;//Changes the value to a percentage.
    }//GEN-LAST:event_percentJumpedSliderStateChanged

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        DrawingArea.i = 0;//Restarts the simulation with the new values.
    }//GEN-LAST:event_startButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);//Quits the program
    }//GEN-LAST:event_quitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider percentJumpedSlider;
    private javax.swing.JButton quitButton;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton startButton;
    private javax.swing.JSlider wallDistanceSlider;
    // End of variables declaration//GEN-END:variables
}
